# -*- coding: utf-8 -*-
"""algebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RR9I4wdQitxIMfTFcBOCfNXWaYKoAmrV
"""
# como parte de estudio del libro de Seymour Lipschutz 
# se propone escribir formulas en BASIC para diferentes expresiones algebraicas
# como ejercicio se excriben las mismas expresiones algebraicas en JavaScript
# Fuente:Lipschutz, S. (1992) Algoritmos, diagramas de flujo, programas n
# pseudocodigo en McGraw-Hill(E.) Matematicas para la computacion (1era Ed., p 125)

# Literal (a)
x=1
y=2
resultado = x**2 +y**2
print (resultado)

#literal (b)
resultado = (x+y)**2
print (resultado)

#literal (c)
a=1
b=2
c=3
d=4
resultado = (2*a*b)/(c+d)
print (resultado)

#literal (d)
t=1
n=2
resultado= t**(n+1)
print (resultado)

#literal (e)
z=3
resultado = x/(y*z)
print (resultado)

#literal (f)
resultado = (x**2 +2*x*y -y**2)**5
print (resultado)

