# -*- coding: utf-8 -*-
"""algebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RR9I4wdQitxIMfTFcBOCfNXWaYKoAmrV
"""

# Literal (a)
x=1
y=2
resultado = x**2 +y**2
print (resultado)

#literal (b)
resultado = (x+y)**2
print (resultado)

#literal (c)
a=1
b=2
c=3
d=4
resultado = (2*a*b)/(c+d)
print (resultado)

#literal (d)
t=1
n=2
resultado= t**(n+1)
print (resultado)

#literal (e)
z=3
resultado = x/(y*z)
print (resultado)

#literal (f)
resultado = (x**2 +2*x*y -y**2)**5
print (resultado)

